/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

/*
 * #%L
 * OpenNaaS :: CIM Model
 * %%
 * Copyright (C) 2007 - 2014 Fundació Privada i2CAT, Internet i Innovació a Catalunya
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.io.Serializable;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class HostedService as well as methods comparable to the
 * invokeMethods defined for this class. This Class implements the HostedServiceBean Interface. The CIM class HostedService is described as follows:
 * 
 * CIM_HostedService is an association between a Service and the System on which the functionality is located. The cardinality of this association is
 * one-to-many. A System can host many Services. Services are weak with respect to their hosting System. Heuristic: A Service is hosted on the System
 * where the LogicalDevices or SoftwareFeatures that implement the Service are located. The model does not represent Services hosted across multiple
 * systems. The model is as an ApplicationSystem that acts as an aggregation point for Services that are each located on a single host.
 */
public class HostedService extends HostedDependency implements Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2449147270544793244L;

	/**
	 * This constructor creates a HostedServiceBeanImpl Class which implements the HostedServiceBean Interface, and encapsulates the CIM class
	 * HostedService in a Java Bean. The CIM class HostedService is described as follows:
	 * 
	 * CIM_HostedService is an association between a Service and the System on which the functionality is located. The cardinality of this association
	 * is one-to-many. A System can host many Services. Services are weak with respect to their hosting System. Heuristic: A Service is hosted on the
	 * System where the LogicalDevices or SoftwareFeatures that implement the Service are located. The model does not represent Services hosted across
	 * multiple systems. The model is as an ApplicationSystem that acts as an aggregation point for Services that are each located on a single host.
	 */
	public HostedService() {
	};

	/**
	 * This method create an Association of the type HostedService between one System object and Service object
	 */
	public static HostedService link(System antecedent, Service dependent) {

		return (HostedService) Association.link(HostedService.class, antecedent, dependent);
	}// link

} // Class HostedService
