/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Tue Jan 04 
 * 15:37:42 CET 2011. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import javax.persistence.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class BGPAdminDistance as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * BGPAdminDistanceBean Interface. The CIM class BGPAdminDistance is 
 * described as follows: 
 * 
 * This is a specialization of the Dependency association, and defines the 
 * relationship between a BGPService and the AdministrativeDistances that it 
 * uses to control the (BGP) routing decisions that it makes. 
 */
    @Entity
public class BGPAdminDistance extends Dependency implements Serializable {

    /**
     * This constructor creates a BGPAdminDistanceBeanImpl Class which 
     * implements the BGPAdminDistanceBean Interface, and encapsulates the 
     * CIM class BGPAdminDistance in a Java Bean. The CIM class 
     * BGPAdminDistance is described as follows: 
     * 
     * This is a specialization of the Dependency association, and defines the 
     * relationship between a BGPService and the AdministrativeDistances that 
     * it uses to control the (BGP) routing decisions that it makes. 
     */
    public BGPAdminDistance(){};
    /**
     * This method create an Association of the type BGPAdminDistance between 
     * one AdministrativeDistance object and BGPService object 
     */
    public Association link(AdministrativeDistance antecedent,BGPService 
	dependent){

    return super.link(BGPAdminDistance.class,antecedent,dependent);
    }//link

} // Class BGPAdminDistance
