/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Fri Dec 03 
 * 14:18:55 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class BGPRoutingPolicy as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * BGPRoutingPolicyBean Interface. The CIM class BGPRoutingPolicy is 
 * described as follows: 
 * 
 * This is a specialization of the Dependency association, and defines the 
 * relationship between a BGPService and the RoutingPolicy that control it. 
 */
public class BGPRoutingPolicy extends Dependency implements Serializable {

    /**
     * This constructor creates a BGPRoutingPolicyBeanImpl Class which 
     * implements the BGPRoutingPolicyBean Interface, and encapsulates the 
     * CIM class BGPRoutingPolicy in a Java Bean. The CIM class 
     * BGPRoutingPolicy is described as follows: 
     * 
     * This is a specialization of the Dependency association, and defines the 
     * relationship between a BGPService and the RoutingPolicy that control 
     * it. 
     */
    public BGPRoutingPolicy(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Antecedent. 
     */
    private RoutingPolicy antecedent;
    /**
     * This method returns the BGPRoutingPolicy.Antecedent property value. 
     * This property is described as follows: 
     * 
     * The BGP routing policy object.
     * 
     * @return	CIM_RoutingPolicy	current Antecedent property 
     * value 
     * @exception	Exception	
     */
    public RoutingPolicy getAntecedent(){

    return (RoutingPolicy)antecedent;
    } // getAntecedent

    /**
     * This method sets the BGPRoutingPolicy.Antecedent property value. This 
     * property is described as follows: 
     * 
     * The BGP routing policy object.
     * 
     * @param	CIM_RoutingPolicy	new Antecedent property value
     * @exception	Exception	
     */
    public void setAntecedent(RoutingPolicy antecedent) {

    this.antecedent = antecedent;
    } // setAntecedent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Dependent. 
     */
    private BGPService dependent;
    /**
     * This method returns the BGPRoutingPolicy.Dependent property value. This 
     * property is described as follows: 
     * 
     * The BGPService that operates according to the routing policy.
     * 
     * @return	CIM_BGPService	current Dependent property value
     * @exception	Exception	
     */
    public BGPService getDependent(){

    return (BGPService)dependent;
    } // getDependent

    /**
     * This method sets the BGPRoutingPolicy.Dependent property value. This 
     * property is described as follows: 
     * 
     * The BGPService that operates according to the routing policy.
     * 
     * @param	CIM_BGPService	new Dependent property value
     * @exception	Exception	
     */
    public void setDependent(BGPService dependent) {

    this.dependent = dependent;
    } // setDependent



} // Class BGPRoutingPolicy
