/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Mon Nov 29 
 * 11:50:57 CET 2010. 
 */

package net.i2cat.mantychore.model;

import javax.wbem.client.*;
import javax.wbem.cim.*;
import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class BGPService as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * BGPServiceBean Interface. The CIM class BGPService is described as 
 * follows: 
 * 
 * This class is used to represent the basic operation of BGP. It is derived 
 * from RouteCalculationService, the superclass of all routing protocols. 
 */
public class BGPService extends RouteCalculationService implements 
    Serializable {

    /**
     * This constructor creates a BGPServiceBeanImpl Class which implements 
     * the BGPServiceBean Interface, and encapsulates the CIM class 
     * BGPService in a Java Bean. The CIM class BGPService is described as 
     * follows: 
     * 
     * This class is used to represent the basic operation of BGP. It is 
     * derived from RouteCalculationService, the superclass of all routing 
     * protocols. 
     */
    public BGPService(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property BGPVersion. 
     */
    private Byte bGPVersion;
    /**
     * This method returns the BGPService.BGPVersion property value. This 
     * property is described as follows: 
     * 
     * The BGPVersion property defines the version of BGP that this router is 
     * using. This is part of the BGP peer negotiation process). 
     * 
     * @return	Byte	current BGPVersion property value
     * @exception	Exception	
     */
    public Byte getBGPVersion(){

    return this.bGPVersion;
    } // getBGPVersion

    /**
     * This method sets the BGPService.BGPVersion property value. This 
     * property is described as follows: 
     * 
     * The BGPVersion property defines the version of BGP that this router is 
     * using. This is part of the BGP peer negotiation process). 
     * 
     * @param	Byte	new BGPVersion property value
     * @exception	Exception	
     */
    public void setBGPVersion(Byte bGPVersion) {

    this.bGPVersion = bGPVersion;
    } // setBGPVersion


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property LastErrorCode. 
     */

    public enum LastErrorCode{
    NONE,
    MESSAGE_HEADER_ERROR,
    OPEN_MESSAGE_ERROR,
    UPDATE_MESSAGE_ERROR,
    HOLD_TIMER_EXPIRED,
    FINITE_STATE_MACHINE_ERROR,
    CEASE
    }LastErrorCode lastErrorCode;
    /**
     * This method returns the BGPService.LastErrorCode property value. This 
     * property is described as follows: 
     * 
     * BGP sends errors using a NOTIFICATION message. This message contains an 
     * error code, an error subcode, and error data. The error code defines 
     * the type of the notification. The 'Cease' error is for all fatal 
     * errors that are not one of the other five types of errors. For several 
     * of the errors, subcode information is also enumerated in other 
     * properties of this class. 
     * 
     * @return	short	current LastErrorCode property value
     * @exception	Exception	
     */
    public LastErrorCode getLastErrorCode(){

    return this.lastErrorCode;
    } // getLastErrorCode

    /**
     * This method sets the BGPService.LastErrorCode property value. This 
     * property is described as follows: 
     * 
     * BGP sends errors using a NOTIFICATION message. This message contains an 
     * error code, an error subcode, and error data. The error code defines 
     * the type of the notification. The 'Cease' error is for all fatal 
     * errors that are not one of the other five types of errors. For several 
     * of the errors, subcode information is also enumerated in other 
     * properties of this class. 
     * 
     * @param	short	new LastErrorCode property value
     * @exception	Exception	
     */
    public void setLastErrorCode(LastErrorCode lastErrorCode){

    this.lastErrorCode = lastErrorCode;
    } // setLastErrorCode


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property LastMessageErrorSubCode. 
     */

    public enum LastMessageErrorSubCode{
    NONE,
    CONNECTION_NOT_SYNCHRONIZED,
    BAD_MESSAGE_LENGTH,
    BAD_MESSAGE_TYPE
    }LastMessageErrorSubCode lastMessageErrorSubCode;
    /**
     * This method returns the BGPService.LastMessageErrorSubCode property 
     * value. This property is described as follows: 
     * 
     * This defines the BGP error subcode for message header errors 
     * (LastErrorCode = 1). If LastErrorCode is any other value, then this 
     * property should be set to NULL. 
     * 
     * @return	short	current LastMessageErrorSubCode property 
     * value 
     * @exception	Exception	
     */
    public LastMessageErrorSubCode getLastMessageErrorSubCode(){

    return this.lastMessageErrorSubCode;
    } // getLastMessageErrorSubCode

    /**
     * This method sets the BGPService.LastMessageErrorSubCode property value. 
     * This property is described as follows: 
     * 
     * This defines the BGP error subcode for message header errors 
     * (LastErrorCode = 1). If LastErrorCode is any other value, then this 
     * property should be set to NULL. 
     * 
     * @param	short	new LastMessageErrorSubCode property value
     * @exception	Exception	
     */
    public void setLastMessageErrorSubCode(LastMessageErrorSubCode 
	lastMessageErrorSubCode){

    this.lastMessageErrorSubCode = lastMessageErrorSubCode;
    } // setLastMessageErrorSubCode


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property LastOpenErrorSubCode. 
     */

    public enum LastOpenErrorSubCode{
    NONE,
    UNSUPPORTED_VERSION_NUMBER,
    BAD_PEER_AS,
    BAD_BGP_IDENTIFIER,
    UNSUPPORTED_OPTIONAL_PARAMETER,
    AUTHENTICATION_FAILURE,
    UNACCEPTABLE_HOLD_TIME
    }LastOpenErrorSubCode lastOpenErrorSubCode;
    /**
     * This method returns the BGPService.LastOpenErrorSubCode property value. 
     * This property is described as follows: 
     * 
     * This defines the BGP error subcode for OPEN message errors 
     * (LastErrorCode = 2). If LastErrorCode is any other value, then this 
     * property should be set to NULL. 
     * 
     * @return	short	current LastOpenErrorSubCode property value
     * @exception	Exception	
     */
    public LastOpenErrorSubCode getLastOpenErrorSubCode(){

    return this.lastOpenErrorSubCode;
    } // getLastOpenErrorSubCode

    /**
     * This method sets the BGPService.LastOpenErrorSubCode property value. 
     * This property is described as follows: 
     * 
     * This defines the BGP error subcode for OPEN message errors 
     * (LastErrorCode = 2). If LastErrorCode is any other value, then this 
     * property should be set to NULL. 
     * 
     * @param	short	new LastOpenErrorSubCode property value
     * @exception	Exception	
     */
    public void setLastOpenErrorSubCode(LastOpenErrorSubCode 
	lastOpenErrorSubCode){

    this.lastOpenErrorSubCode = lastOpenErrorSubCode;
    } // setLastOpenErrorSubCode


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property LastUpdateErrorSubCode. 
     */

    public enum LastUpdateErrorSubCode{
    NONE,
    MALFORMED_ATTRIBUTE_LIST,
    UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE,
    MISSING_WELL_KNOWN_ATTRIBUTE,
    ATTRIBUTE_FLAGS_ERROR,
    ATTRIBUTE_LENGTH_ERROR,
    INVALID_ORIGIN_ATTRIBUTE,
    AS_ROUTING_LOOP,
    INVALID_NEXT_HOP_ATTRIBUTE,
    OPTIONAL_ATTRIBUTE_ERROR,
    INVALID_NETWORK_FIELD,
    MALFORMED_AS_PATH
    }LastUpdateErrorSubCode lastUpdateErrorSubCode;
    /**
     * This method returns the BGPService.LastUpdateErrorSubCode property 
     * value. This property is described as follows: 
     * 
     * This defines the BGP error subcode for UPDATE message errors 
     * (LastErrorCode = 3). If LastErrorCode is any other value, then this 
     * property should be set to NULL. 
     * 
     * @return	short	current LastUpdateErrorSubCode property 
     * value 
     * @exception	Exception	
     */
    public LastUpdateErrorSubCode getLastUpdateErrorSubCode(){

    return this.lastUpdateErrorSubCode;
    } // getLastUpdateErrorSubCode

    /**
     * This method sets the BGPService.LastUpdateErrorSubCode property value. 
     * This property is described as follows: 
     * 
     * This defines the BGP error subcode for UPDATE message errors 
     * (LastErrorCode = 3). If LastErrorCode is any other value, then this 
     * property should be set to NULL. 
     * 
     * @param	short	new LastUpdateErrorSubCode property value
     * @exception	Exception	
     */
    public void setLastUpdateErrorSubCode(LastUpdateErrorSubCode 
	lastUpdateErrorSubCode){

    this.lastUpdateErrorSubCode = lastUpdateErrorSubCode;
    } // setLastUpdateErrorSubCode



} // Class BGPService
