/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Mon Nov 29 
 * 11:50:57 CET 2010. 
 */

package net.i2cat.mantychore.model;

import javax.wbem.client.*;
import javax.wbem.cim.*;
import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class Confederation as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * ConfederationBean Interface. The CIM class Confederation is described as 
 * follows: 
 * 
 * The BGP speakers in an AS are required to be fully meshed. This can lead to 
 * a huge number of TCP connections per router. One way to reduce the peering 
 * requirements is to use a confederation. A confederation effectively 
 * partitions one AS into a group of 'sub-ASs'. This enables all of the 
 * benefits of IBGP to be applied inside the confederation, while enabling 
 * EBGP to be run between each confederation. It also enables certain BGP 
 * attribute values to be preserved between confederations. However, to the 
 * outside world, the AS with its confederations appear to be a single AS. 
 */
public class Confederation extends SystemComponent implements Serializable {

    /**
     * This constructor creates a ConfederationBeanImpl Class which implements 
     * the ConfederationBean Interface, and encapsulates the CIM class 
     * Confederation in a Java Bean. The CIM class Confederation is described 
     * as follows: 
     * 
     * The BGP speakers in an AS are required to be fully meshed. This can 
     * lead to a huge number of TCP connections per router. One way to reduce 
     * the peering requirements is to use a confederation. A confederation 
     * effectively partitions one AS into a group of 'sub-ASs'. This enables 
     * all of the benefits of IBGP to be applied inside the confederation, 
     * while enabling EBGP to be run between each confederation. It also 
     * enables certain BGP attribute values to be preserved between 
     * confederations. However, to the outside world, the AS with its 
     * confederations appear to be a single AS. 
     */
    public Confederation(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property GroupComponent. 
     */
    private AutonomousSystem groupComponent;
    /**
     * This method returns the Confederation.GroupComponent property value. 
     * This property is described as follows: 
     * 
     * The AutonomousSystem that contains the confederations.
     * 
     * @return	CIM_AutonomousSystem	current GroupComponent 
     * property value 
     * @exception	Exception	
     */
    public AutonomousSystem getGroupComponent(){

    return (AutonomousSystem)groupComponent;
    } // getGroupComponent

    /**
     * This method sets the Confederation.GroupComponent property value. This 
     * property is described as follows: 
     * 
     * The AutonomousSystem that contains the confederations.
     * 
     * @param	CIM_AutonomousSystem	new GroupComponent property 
     * value 
     * @exception	Exception	
     */
    public void setGroupComponent(AutonomousSystem groupComponent) {

    this.groupComponent = groupComponent;
    } // setGroupComponent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property PartComponent. 
     */
    private AutonomousSystem partComponent;
    /**
     * This method returns the Confederation.PartComponent property value. 
     * This property is described as follows: 
     * 
     * The Confederation within the AutonomousSystem.
     * 
     * @return	CIM_AutonomousSystem	current PartComponent 
     * property value 
     * @exception	Exception	
     */
    public AutonomousSystem getPartComponent(){

    return (AutonomousSystem)partComponent;
    } // getPartComponent

    /**
     * This method sets the Confederation.PartComponent property value. This 
     * property is described as follows: 
     * 
     * The Confederation within the AutonomousSystem.
     * 
     * @param	CIM_AutonomousSystem	new PartComponent property 
     * value 
     * @exception	Exception	
     */
    public void setPartComponent(AutonomousSystem partComponent) {

    this.partComponent = partComponent;
    } // setPartComponent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property ParentASNumber. 
     */
    private int parentASNumber;
    /**
     * This method returns the Confederation.ParentASNumber property value. 
     * This property is described as follows: 
     * 
     * A unique identifier of the AutonomousSystem that contains the 
     * confederations. 
     * 
     * @return	int	current ParentASNumber property value
     * @exception	Exception	
     */
    public int getParentASNumber(){

    return this.parentASNumber;
    } // getParentASNumber

    /**
     * This method sets the Confederation.ParentASNumber property value. This 
     * property is described as follows: 
     * 
     * A unique identifier of the AutonomousSystem that contains the 
     * confederations. 
     * 
     * @param	int	new ParentASNumber property value
     * @exception	Exception	
     */
    public void setParentASNumber(int parentASNumber) {

    this.parentASNumber = parentASNumber;
    } // setParentASNumber


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property ChildASNumber. 
     */
    private int childASNumber;
    /**
     * This method returns the Confederation.ChildASNumber property value. 
     * This property is described as follows: 
     * 
     * A unique identifier of the Confederation within the AutonomousSystem.
     * 
     * @return	int	current ChildASNumber property value
     * @exception	Exception	
     */
    public int getChildASNumber(){

    return this.childASNumber;
    } // getChildASNumber

    /**
     * This method sets the Confederation.ChildASNumber property value. This 
     * property is described as follows: 
     * 
     * A unique identifier of the Confederation within the AutonomousSystem.
     * 
     * @param	int	new ChildASNumber property value
     * @exception	Exception	
     */
    public void setChildASNumber(int childASNumber) {

    this.childASNumber = childASNumber;
    } // setChildASNumber



} // Class Confederation
