/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Mon Nov 29 
 * 11:50:57 CET 2010. 
 */

package net.i2cat.mantychore.model;

import javax.wbem.client.*;
import javax.wbem.cim.*;
import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class ContainedLocation as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * ContainedLocationBean Interface. The CIM class ContainedLocation is 
 * described as follows: 
 * 
 * ContainedLocation defines one location in the context of another. For 
 * example, a campus might 'contain' a building, which in turn 'contains' a 
 * floor. 
 */
public class ContainedLocation extends Component implements Serializable {

    /**
     * This constructor creates a ContainedLocationBeanImpl Class which 
     * implements the ContainedLocationBean Interface, and encapsulates the 
     * CIM class ContainedLocation in a Java Bean. The CIM class 
     * ContainedLocation is described as follows: 
     * 
     * ContainedLocation defines one location in the context of another. For 
     * example, a campus might 'contain' a building, which in turn 'contains' 
     * a floor. 
     */
    public ContainedLocation(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property GroupComponent. 
     */
    private Location groupComponent;
    /**
     * This method returns the ContainedLocation.GroupComponent property 
     * value. This property is described as follows: 
     * 
     * The containing location.
     * 
     * @return	CIM_Location	current GroupComponent property 
     * value 
     * @exception	Exception	
     */
    public Location getGroupComponent(){

    return (Location)groupComponent;
    } // getGroupComponent

    /**
     * This method sets the ContainedLocation.GroupComponent property value. 
     * This property is described as follows: 
     * 
     * The containing location.
     * 
     * @param	CIM_Location	new GroupComponent property value
     * @exception	Exception	
     */
    public void setGroupComponent(Location groupComponent) {

    this.groupComponent = groupComponent;
    } // setGroupComponent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property PartComponent. 
     */
    private Location partComponent;
    /**
     * This method returns the ContainedLocation.PartComponent property value. 
     * This property is described as follows: 
     * 
     * The contained location.
     * 
     * @return	CIM_Location	current PartComponent property value
     * @exception	Exception	
     */
    public Location getPartComponent(){

    return (Location)partComponent;
    } // getPartComponent

    /**
     * This method sets the ContainedLocation.PartComponent property value. 
     * This property is described as follows: 
     * 
     * The contained location.
     * 
     * @param	CIM_Location	new PartComponent property value
     * @exception	Exception	
     */
    public void setPartComponent(Location partComponent) {

    this.partComponent = partComponent;
    } // setPartComponent



} // Class ContainedLocation
