/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Mon Nov 29 
 * 11:50:57 CET 2010. 
 */

package net.i2cat.mantychore.model;

import javax.wbem.client.*;
import javax.wbem.cim.*;
import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class DefaultSetting as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * DefaultSettingBean Interface. The CIM class DefaultSetting is described as 
 * follows: 
 * 
 * DefaultSetting represents the association between a ManagedSystemElement 
 * and the single Setting class that is defined to be the default setting for 
 * this Element. 
 */
public class DefaultSetting extends ElementSetting implements Serializable {

    /**
     * This constructor creates a DefaultSettingBeanImpl Class which 
     * implements the DefaultSettingBean Interface, and encapsulates the CIM 
     * class DefaultSetting in a Java Bean. The CIM class DefaultSetting is 
     * described as follows: 
     * 
     * DefaultSetting represents the association between a 
     * ManagedSystemElement and the single Setting class that is defined to 
     * be the default setting for this Element. 
     */
    public DefaultSetting(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Setting. 
     */
    private Setting setting;
    /**
     * This method returns the DefaultSetting.Setting property value. This 
     * property is described as follows: 
     * 
     * The Setting object that is the default.
     * 
     * @return	CIM_Setting	current Setting property value
     * @exception	Exception	
     */
    public Setting getSetting(){

    return (Setting)setting;
    } // getSetting

    /**
     * This method sets the DefaultSetting.Setting property value. This 
     * property is described as follows: 
     * 
     * The Setting object that is the default.
     * 
     * @param	CIM_Setting	new Setting property value
     * @exception	Exception	
     */
    public void setSetting(Setting setting) {

    this.setting = setting;
    } // setSetting



} // Class DefaultSetting
