/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Mon Jan 03 
 * 16:22:03 CET 2011. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import javax.persistence.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class InstalledSoftwareIdentity as well as methods comparable 
 * to the invokeMethods defined for this class. This Class implements the 
 * InstalledSoftwareIdentityBean Interface. The CIM class 
 * InstalledSoftwareIdentity is described as follows: 
 * 
 * The InstalledSoftwareIdentity association identifies the System on which a 
 * SoftwareIdentity is installed. This class is a corollary to 
 * InstalledSoftwareElement, but deals with the asset aspects of software (as 
 * indicated by SoftwareIdentity), versus the deployment aspects (as 
 * indicated by SoftwareElement). 
 */
    @Entity
public class InstalledSoftwareIdentity extends Association implements 
    Serializable {

    /**
     * This constructor creates a InstalledSoftwareIdentityBeanImpl Class 
     * which implements the InstalledSoftwareIdentityBean Interface, and 
     * encapsulates the CIM class InstalledSoftwareIdentity in a Java Bean. 
     * The CIM class InstalledSoftwareIdentity is described as follows: 
     * 
     * The InstalledSoftwareIdentity association identifies the System on 
     * which a SoftwareIdentity is installed. This class is a corollary to 
     * InstalledSoftwareElement, but deals with the asset aspects of software 
     * (as indicated by SoftwareIdentity), versus the deployment aspects (as 
     * indicated by SoftwareElement). 
     */
    public InstalledSoftwareIdentity(){};
    /**
     * This method create an Association of the type InstalledSoftwareIdentity 
     * between one System object and SoftwareIdentity object 
     */
    public Association link(System system,SoftwareIdentity 
	installedSoftware){

    return 
	super.link(InstalledSoftwareIdentity.class,system,installedSoftware);
    }//link

} // Class InstalledSoftwareIdentity
