/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Tue Jan 04 
 * 15:37:42 CET 2011. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import javax.persistence.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class PhysicalElementLocation as well as methods comparable to 
 * the invokeMethods defined for this class. This Class implements the 
 * PhysicalElementLocationBean Interface. The CIM class 
 * PhysicalElementLocation is described as follows: 
 * 
 * PhysicalElementLocation associates a PhysicalElement with a Location object 
 * for inventory or replacement purposes. 
 */
    @Entity
public class PhysicalElementLocation extends ElementLocation implements 
    Serializable {

    /**
     * This constructor creates a PhysicalElementLocationBeanImpl Class which 
     * implements the PhysicalElementLocationBean Interface, and encapsulates 
     * the CIM class PhysicalElementLocation in a Java Bean. The CIM class 
     * PhysicalElementLocation is described as follows: 
     * 
     * PhysicalElementLocation associates a PhysicalElement with a Location 
     * object for inventory or replacement purposes. 
     */
    public PhysicalElementLocation(){};
    /**
     * This method create an Association of the type PhysicalElementLocation 
     * between one PhysicalElement object and Location object 
     */
    public Association link(PhysicalElement element,Location 
	physicalLocation){

    return 
	super.link(PhysicalElementLocation.class,element,physicalLocation);
    }//link

} // Class PhysicalElementLocation
