/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Fri Dec 03 
 * 14:18:55 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class ProductComponent as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * ProductComponentBean Interface. The CIM class ProductComponent is 
 * described as follows: 
 * 
 * The CIM_ProductComponent association defines a containment and component 
 * relationship among Products. For example, a Product may come bundled with 
 * other Products. Note that this association duplicates ProductParentChild. 
 * The latter association is maintained for legacy reasons. This association, 
 * ProductComponent, is added for ease of query and modeling consistency. 
 * Using ProductComponent, an application can query for all Component 
 * relationships for a Product, versus querying the various Component 
 * relationships AND ProductParentChild. 
 */
public class ProductComponent extends Component implements Serializable {

    /**
     * This constructor creates a ProductComponentBeanImpl Class which 
     * implements the ProductComponentBean Interface, and encapsulates the 
     * CIM class ProductComponent in a Java Bean. The CIM class 
     * ProductComponent is described as follows: 
     * 
     * The CIM_ProductComponent association defines a containment and 
     * component relationship among Products. For example, a Product may come 
     * bundled with other Products. Note that this association duplicates 
     * ProductParentChild. The latter association is maintained for legacy 
     * reasons. This association, ProductComponent, is added for ease of 
     * query and modeling consistency. Using ProductComponent, an application 
     * can query for all Component relationships for a Product, versus 
     * querying the various Component relationships AND ProductParentChild. 
     */
    public ProductComponent(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property GroupComponent. 
     */
    private Product groupComponent;
    /**
     * This method returns the ProductComponent.GroupComponent property value. 
     * This property is described as follows: 
     * 
     * The Product which contains another Product as a component. The 
     * cardinality of this reference takes the default values (no minimum or 
     * maximum) since an instance of Product can describe either a general 
     * product type, or a specific item that is acquired. In the case of a 
     * specific item, a cardinality of Max(1) is indicated. However, when 
     * dealing with the general description/templating of a Product, then it 
     * may be a component of several others and a cardinality of Max(1) would 
     * be invalid. 
     * 
     * @return	CIM_Product	current GroupComponent property value
     * @exception	Exception	
     */
    public Product getGroupComponent(){

    return (Product)groupComponent;
    } // getGroupComponent

    /**
     * This method sets the ProductComponent.GroupComponent property value. 
     * This property is described as follows: 
     * 
     * The Product which contains another Product as a component. The 
     * cardinality of this reference takes the default values (no minimum or 
     * maximum) since an instance of Product can describe either a general 
     * product type, or a specific item that is acquired. In the case of a 
     * specific item, a cardinality of Max(1) is indicated. However, when 
     * dealing with the general description/templating of a Product, then it 
     * may be a component of several others and a cardinality of Max(1) would 
     * be invalid. 
     * 
     * @param	CIM_Product	new GroupComponent property value
     * @exception	Exception	
     */
    public void setGroupComponent(Product groupComponent) {

    this.groupComponent = groupComponent;
    } // setGroupComponent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property PartComponent. 
     */
    private Product partComponent;
    /**
     * This method returns the ProductComponent.PartComponent property value. 
     * This property is described as follows: 
     * 
     * The contained Product.
     * 
     * @return	CIM_Product	current PartComponent property value
     * @exception	Exception	
     */
    public Product getPartComponent(){

    return (Product)partComponent;
    } // getPartComponent

    /**
     * This method sets the ProductComponent.PartComponent property value. 
     * This property is described as follows: 
     * 
     * The contained Product.
     * 
     * @param	CIM_Product	new PartComponent property value
     * @exception	Exception	
     */
    public void setPartComponent(Product partComponent) {

    this.partComponent = partComponent;
    } // setPartComponent



} // Class ProductComponent
