/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Tue Nov 30 
 * 10:54:51 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class QoSConditioningSubService as well as methods comparable 
 * to the invokeMethods defined for this class. This Class implements the 
 * QoSConditioningSubServiceBean Interface. The CIM class 
 * QoSConditioningSubService is described as follows: 
 * 
 * A QoSService utilizes underlying ConditioningServices as part of its 
 * overall functionality. This is modeled using the QoSConditioningSubService 
 * association. Note that a ConditioningService may only be part of a single 
 * QoSService - the cardinality on the QoSService reference is Max (1). 
 */
public class QoSConditioningSubService extends ServiceComponent implements 
    Serializable {

    /**
     * This constructor creates a QoSConditioningSubServiceBeanImpl Class 
     * which implements the QoSConditioningSubServiceBean Interface, and 
     * encapsulates the CIM class QoSConditioningSubService in a Java Bean. 
     * The CIM class QoSConditioningSubService is described as follows: 
     * 
     * A QoSService utilizes underlying ConditioningServices as part of its 
     * overall functionality. This is modeled using the 
     * QoSConditioningSubService association. Note that a ConditioningService 
     * may only be part of a single QoSService - the cardinality on the 
     * QoSService reference is Max (1). 
     */
    public QoSConditioningSubService(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property GroupComponent. 
     */
    private QoSService groupComponent;
    /**
     * This method returns the QoSConditioningSubService.GroupComponent 
     * property value. This property is described as follows: 
     * 
     * This aggregation identifies the set of ConditioningServices that 
     * together condition traffic for a particular QoSService. 
     * 
     * @return	CIM_QoSService	current GroupComponent property 
     * value 
     * @exception	Exception	
     */
    public QoSService getGroupComponent(){

    return (QoSService)groupComponent;
    } // getGroupComponent

    /**
     * This method sets the QoSConditioningSubService.GroupComponent property 
     * value. This property is described as follows: 
     * 
     * This aggregation identifies the set of ConditioningServices that 
     * together condition traffic for a particular QoSService. 
     * 
     * @param	CIM_QoSService	new GroupComponent property value
     * @exception	Exception	
     */
    public void setGroupComponent(QoSService groupComponent) {

    this.groupComponent = groupComponent;
    } // setGroupComponent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property PartComponent. 
     */
    private ConditioningService partComponent;
    /**
     * This method returns the QoSConditioningSubService.PartComponent 
     * property value. This property is described as follows: 
     * 
     * The ConditioningService.
     * 
     * @return	CIM_ConditioningService	current PartComponent 
     * property value 
     * @exception	Exception	
     */
    public ConditioningService getPartComponent(){

    return (ConditioningService)partComponent;
    } // getPartComponent

    /**
     * This method sets the QoSConditioningSubService.PartComponent property 
     * value. This property is described as follows: 
     * 
     * The ConditioningService.
     * 
     * @param	CIM_ConditioningService	new PartComponent property 
     * value 
     * @exception	Exception	
     */
    public void setPartComponent(ConditioningService partComponent) {

    this.partComponent = partComponent;
    } // setPartComponent



} // Class QoSConditioningSubService
