/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Fri Dec 03 
 * 14:18:55 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class QueuingService as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * QueuingServiceBean Interface. The CIM class QueuingService is described as 
 * follows: 
 * 
 * QueuingService represents the ability to queue network traffic, and to 
 * specify the characteristics for determining long-term congestion. It is 
 * modeled as a ConditioningService so that it can be aggregated into a 
 * QoSService (using the QoSConditioningSubService association). This 
 * indicates that its functionality underlies the QoSService. 
 */
public class QueuingService extends ConditioningService implements 
    Serializable {

    /**
     * This constructor creates a QueuingServiceBeanImpl Class which 
     * implements the QueuingServiceBean Interface, and encapsulates the CIM 
     * class QueuingService in a Java Bean. The CIM class QueuingService is 
     * described as follows: 
     * 
     * QueuingService represents the ability to queue network traffic, and to 
     * specify the characteristics for determining long-term congestion. It 
     * is modeled as a ConditioningService so that it can be aggregated into 
     * a QoSService (using the QoSConditioningSubService association). This 
     * indicates that its functionality underlies the QoSService. 
     */
    public QueuingService(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property CurrentQueueDepth. 
     */
    private int currentQueueDepth;
    /**
     * This method returns the QueuingService.CurrentQueueDepth property 
     * value. This property is described as follows: 
     * 
     * Indicates the current depth of this queue in units specified by 
     * DepthUnits. This value may be important in diagnosing unexpected 
     * behavior. 
     * 
     * @return	int	current CurrentQueueDepth property value
     * @exception	Exception	
     */
    public int getCurrentQueueDepth(){

    return this.currentQueueDepth;
    } // getCurrentQueueDepth

    /**
     * This method sets the QueuingService.CurrentQueueDepth property value. 
     * This property is described as follows: 
     * 
     * Indicates the current depth of this queue in units specified by 
     * DepthUnits. This value may be important in diagnosing unexpected 
     * behavior. 
     * 
     * @param	int	new CurrentQueueDepth property value
     * @exception	Exception	
     */
    public void setCurrentQueueDepth(int currentQueueDepth) {

    this.currentQueueDepth = currentQueueDepth;
    } // setCurrentQueueDepth


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property DepthUnits. 
     */

    public enum DepthUnits{
    BYTES,
    PACKETS
    }
 public DepthUnits depthUnits;
    /**
     * This method returns the QueuingService.DepthUnits property value. This 
     * property is described as follows: 
     * 
     * DepthUnits is an enumerated integer that identifies the units for the 
     * CurrentQueueDepth property. The values are either bytes (1) or packets 
     * (2). 
     * 
     * @return	short	current DepthUnits property value
     * @exception	Exception	
     */
    public DepthUnits getDepthUnits(){

    return this.depthUnits;
    } // getDepthUnits

    /**
     * This method sets the QueuingService.DepthUnits property value. This 
     * property is described as follows: 
     * 
     * DepthUnits is an enumerated integer that identifies the units for the 
     * CurrentQueueDepth property. The values are either bytes (1) or packets 
     * (2). 
     * 
     * @param	short	new DepthUnits property value
     * @exception	Exception	
     */
    public void setDepthUnits(DepthUnits depthUnits){

    this.depthUnits = depthUnits;
    } // setDepthUnits



} // Class QueuingService
