/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Tue Nov 30 
 * 10:54:51 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class ReflectorClientService as well as methods comparable to 
 * the invokeMethods defined for this class. This Class implements the 
 * ReflectorClientServiceBean Interface. The CIM class ReflectorClientService 
 * is described as follows: 
 * 
 * This association will serve as the base class for handling BGP routing 
 * information for clients of the reflector of this Cluster. 
 */
public class ReflectorClientService extends Dependency implements Serializable 
    {

    /**
     * This constructor creates a ReflectorClientServiceBeanImpl Class which 
     * implements the ReflectorClientServiceBean Interface, and encapsulates 
     * the CIM class ReflectorClientService in a Java Bean. The CIM class 
     * ReflectorClientService is described as follows: 
     * 
     * This association will serve as the base class for handling BGP routing 
     * information for clients of the reflector of this Cluster. 
     */
    public ReflectorClientService(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Antecedent. 
     */
    private BGPCluster antecedent;
    /**
     * This method returns the ReflectorClientService.Antecedent property 
     * value. This property is described as follows: 
     * 
     * The Cluster for which this Service is being defined.
     * 
     * @return	CIM_BGPCluster	current Antecedent property value
     * @exception	Exception	
     */
    public BGPCluster getAntecedent(){

    return (BGPCluster)antecedent;
    } // getAntecedent

    /**
     * This method sets the ReflectorClientService.Antecedent property value. 
     * This property is described as follows: 
     * 
     * The Cluster for which this Service is being defined.
     * 
     * @param	CIM_BGPCluster	new Antecedent property value
     * @exception	Exception	
     */
    public void setAntecedent(BGPCluster antecedent) {

    this.antecedent = antecedent;
    } // setAntecedent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Dependent. 
     */
    private BGPService dependent;
    /**
     * This method returns the ReflectorClientService.Dependent property 
     * value. This property is described as follows: 
     * 
     * The BGPService to handles routing information as a client in the 
     * Cluster. 
     * 
     * @return	CIM_BGPService	current Dependent property value
     * @exception	Exception	
     */
    public BGPService getDependent(){

    return (BGPService)dependent;
    } // getDependent

    /**
     * This method sets the ReflectorClientService.Dependent property value. 
     * This property is described as follows: 
     * 
     * The BGPService to handles routing information as a client in the 
     * Cluster. 
     * 
     * @param	CIM_BGPService	new Dependent property value
     * @exception	Exception	
     */
    public void setDependent(BGPService dependent) {

    this.dependent = dependent;
    } // setDependent



} // Class ReflectorClientService
