/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Mon Jan 03 
 * 16:22:03 CET 2011. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import javax.persistence.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class ServiceStatisticalInformation as well as methods 
 * comparable to the invokeMethods defined for this class. This Class 
 * implements the ServiceStatisticalInformationBean Interface. The CIM class 
 * ServiceStatisticalInformation is described as follows: 
 * 
 * Statistical information associated with a Service object or one of its 
 * subclasses. 
 */
    @Entity
public class ServiceStatisticalInformation extends StatisticalInformation 
    implements Serializable {

    /**
     * This constructor creates a ServiceStatisticalInformationBeanImpl Class 
     * which implements the ServiceStatisticalInformationBean Interface, and 
     * encapsulates the CIM class ServiceStatisticalInformation in a Java 
     * Bean. The CIM class ServiceStatisticalInformation is described as 
     * follows: 
     * 
     * Statistical information associated with a Service object or one of its 
     * subclasses. 
     */
    public ServiceStatisticalInformation(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property SystemCreationClassName. 
     */
    private String systemCreationClassName;
    /**
     * This method returns the 
     * ServiceStatisticalInformation.systemCreationClassName property value. 
     * This property is described as follows: 
     * 
     * The scoping System's CreationClassName.
     * 
     * @return	String	current systemCreationClassName property 
     * value 
     * @exception	Exception	
     */
    public String getsystemCreationClassName(){

    return this.systemCreationClassName;
    } // getsystemCreationClassName

    /**
     * This method sets the 
     * ServiceStatisticalInformation.systemCreationClassName property value. 
     * This property is described as follows: 
     * 
     * The scoping System's CreationClassName.
     * 
     * @param	String	new systemCreationClassName property value
     * @exception	Exception	
     */
    public void setsystemCreationClassName(String systemCreationClassName) {

    this.systemCreationClassName = systemCreationClassName;
    } // setsystemCreationClassName


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property SystemName. 
     */
    private String systemName;
    /**
     * This method returns the ServiceStatisticalInformation.systemName 
     * property value. This property is described as follows: 
     * 
     * The scoping System's Name.
     * 
     * @return	String	current systemName property value
     * @exception	Exception	
     */
    public String getsystemName(){

    return this.systemName;
    } // getsystemName

    /**
     * This method sets the ServiceStatisticalInformation.systemName property 
     * value. This property is described as follows: 
     * 
     * The scoping System's Name.
     * 
     * @param	String	new systemName property value
     * @exception	Exception	
     */
    public void setsystemName(String systemName) {

    this.systemName = systemName;
    } // setsystemName


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property ServiceCreationClassName. 
     */
    private String serviceCreationClassName;
    /**
     * This method returns the 
     * ServiceStatisticalInformation.serviceCreationClassName property value. 
     * This property is described as follows: 
     * 
     * The scoping Service's CreationClassName.
     * 
     * @return	String	current serviceCreationClassName property 
     * value 
     * @exception	Exception	
     */
    public String getserviceCreationClassName(){

    return this.serviceCreationClassName;
    } // getserviceCreationClassName

    /**
     * This method sets the 
     * ServiceStatisticalInformation.serviceCreationClassName property value. 
     * This property is described as follows: 
     * 
     * The scoping Service's CreationClassName.
     * 
     * @param	String	new serviceCreationClassName property value
     * @exception	Exception	
     */
    public void setserviceCreationClassName(String serviceCreationClassName) 
	{

    this.serviceCreationClassName = serviceCreationClassName;
    } // setserviceCreationClassName


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property ServiceName. 
     */
    private String serviceName;
    /**
     * This method returns the ServiceStatisticalInformation.serviceName 
     * property value. This property is described as follows: 
     * 
     * The scoping Service's Name.
     * 
     * @return	String	current serviceName property value
     * @exception	Exception	
     */
    public String getserviceName(){

    return this.serviceName;
    } // getserviceName

    /**
     * This method sets the ServiceStatisticalInformation.serviceName property 
     * value. This property is described as follows: 
     * 
     * The scoping Service's Name.
     * 
     * @param	String	new serviceName property value
     * @exception	Exception	
     */
    public void setserviceName(String serviceName) {

    this.serviceName = serviceName;
    } // setserviceName


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property CreationClassName. 
     */
    private String creationClassName;
    /**
     * This method returns the ServiceStatisticalInformation.creationClassName 
     * property value. This property is described as follows: 
     * 
     * CreationClassName indicates the name of the class or the subclass used 
     * in the creation of an instance. When used with the other key 
     * properties of this class, this property allows all instances of this 
     * class and its subclasses to be uniquely identified. 
     * 
     * @return	String	current creationClassName property value
     * @exception	Exception	
     */
    public String getcreationClassName(){

    return this.creationClassName;
    } // getcreationClassName

    /**
     * This method sets the ServiceStatisticalInformation.creationClassName 
     * property value. This property is described as follows: 
     * 
     * CreationClassName indicates the name of the class or the subclass used 
     * in the creation of an instance. When used with the other key 
     * properties of this class, this property allows all instances of this 
     * class and its subclasses to be uniquely identified. 
     * 
     * @param	String	new creationClassName property value
     * @exception	Exception	
     */
    public void setcreationClassName(String creationClassName) {

    this.creationClassName = creationClassName;
    } // setcreationClassName


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Name. 
     */
    private String name;
    /**
     * This method returns the ServiceStatisticalInformation.name property 
     * value. This property is described as follows: 
     * 
     * The Name property, inherited from StatisticalInformation, serves as 
     * part of the object key. 
     * 
     * @return	String	current name property value
     * @exception	Exception	
     */
    public String getname(){

    return (String)name;
    } // getname

    /**
     * This method sets the ServiceStatisticalInformation.name property value. 
     * This property is described as follows: 
     * 
     * The Name property, inherited from StatisticalInformation, serves as 
     * part of the object key. 
     * 
     * @param	String	new name property value
     * @exception	Exception	
     */
    public void setname(String name) {

    this.name = name;
    } // setname



} // Class ServiceStatisticalInformation
