/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Fri Dec 03 
 * 14:18:55 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class SwitchPortStaticForwarding as well as methods comparable 
 * to the invokeMethods defined for this class. This Class implements the 
 * SwitchPortStaticForwardingBean Interface. The CIM class 
 * SwitchPortStaticForwarding is described as follows: 
 * 
 * This association links a static database entry and the SwitchPort to which 
 * the entry applies. 
 */
public class SwitchPortStaticForwarding extends Dependency implements 
    Serializable {

    /**
     * This constructor creates a SwitchPortStaticForwardingBeanImpl Class 
     * which implements the SwitchPortStaticForwardingBean Interface, and 
     * encapsulates the CIM class SwitchPortStaticForwarding in a Java Bean. 
     * The CIM class SwitchPortStaticForwarding is described as follows: 
     * 
     * This association links a static database entry and the SwitchPort to 
     * which the entry applies. 
     */
    public SwitchPortStaticForwarding(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Antecedent. 
     */
    private SwitchPort antecedent;
    /**
     * This method returns the SwitchPortStaticForwarding.Antecedent property 
     * value. This property is described as follows: 
     * 
     * The SwitchPort.
     * 
     * @return	CIM_SwitchPort	current Antecedent property value
     * @exception	Exception	
     */
    public SwitchPort getAntecedent(){

    return (SwitchPort)antecedent;
    } // getAntecedent

    /**
     * This method sets the SwitchPortStaticForwarding.Antecedent property 
     * value. This property is described as follows: 
     * 
     * The SwitchPort.
     * 
     * @param	CIM_SwitchPort	new Antecedent property value
     * @exception	Exception	
     */
    public void setAntecedent(SwitchPort antecedent) {

    this.antecedent = antecedent;
    } // setAntecedent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Dependent. 
     */
    private StaticForwardingEntry dependent;
    /**
     * This method returns the SwitchPortStaticForwarding.Dependent property 
     * value. This property is described as follows: 
     * 
     * StaticForwardingEntry of static database.
     * 
     * @return	CIM_StaticForwardingEntry	current Dependent 
     * property value 
     * @exception	Exception	
     */
    public StaticForwardingEntry getDependent(){

    return (StaticForwardingEntry)dependent;
    } // getDependent

    /**
     * This method sets the SwitchPortStaticForwarding.Dependent property 
     * value. This property is described as follows: 
     * 
     * StaticForwardingEntry of static database.
     * 
     * @param	CIM_StaticForwardingEntry	new Dependent property 
     * value 
     * @exception	Exception	
     */
    public void setDependent(StaticForwardingEntry dependent) {

    this.dependent = dependent;
    } // setDependent



} // Class SwitchPortStaticForwarding
