/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Tue Nov 30 
 * 10:54:51 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class SwitchPortSourceRouting as well as methods comparable to 
 * the invokeMethods defined for this class. This Class implements the 
 * SwitchPortSourceRoutingBean Interface. The CIM class 
 * SwitchPortSourceRouting is described as follows: 
 * 
 * A switch capable of source routing maintains source-routing specific 
 * information about each port. This association represents that information. 
 */
public class SwitchPortSourceRouting extends ServiceSAPDependency implements 
    Serializable {

    /**
     * This constructor creates a SwitchPortSourceRoutingBeanImpl Class which 
     * implements the SwitchPortSourceRoutingBean Interface, and encapsulates 
     * the CIM class SwitchPortSourceRouting in a Java Bean. The CIM class 
     * SwitchPortSourceRouting is described as follows: 
     * 
     * A switch capable of source routing maintains source-routing specific 
     * information about each port. This association represents that 
     * information. 
     */
    public SwitchPortSourceRouting(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Antecedent. 
     */
    private SwitchPort antecedent;
    /**
     * This method returns the SwitchPortSourceRouting.Antecedent property 
     * value. This property is described as follows: 
     * 
     * The SwitchPort.
     * 
     * @return	CIM_SwitchPort	current Antecedent property value
     * @exception	Exception	
     */
    public SwitchPort getAntecedent(){

    return (SwitchPort)antecedent;
    } // getAntecedent

    /**
     * This method sets the SwitchPortSourceRouting.Antecedent property value. 
     * This property is described as follows: 
     * 
     * The SwitchPort.
     * 
     * @param	CIM_SwitchPort	new Antecedent property value
     * @exception	Exception	
     */
    public void setAntecedent(SwitchPort antecedent) {

    this.antecedent = antecedent;
    } // setAntecedent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Dependent. 
     */
    private SourceRoutingService dependent;
    /**
     * This method returns the SwitchPortSourceRouting.Dependent property 
     * value. This property is described as follows: 
     * 
     * The SourceRoutingService.
     * 
     * @return	CIM_SourceRoutingService	current Dependent 
     * property value 
     * @exception	Exception	
     */
    public SourceRoutingService getDependent(){

    return (SourceRoutingService)dependent;
    } // getDependent

    /**
     * This method sets the SwitchPortSourceRouting.Dependent property value. 
     * This property is described as follows: 
     * 
     * The SourceRoutingService.
     * 
     * @param	CIM_SourceRoutingService	new Dependent property 
     * value 
     * @exception	Exception	
     */
    public void setDependent(SourceRoutingService dependent) {

    this.dependent = dependent;
    } // setDependent


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property HopCount. 
     */
    private short hopCount;
    /**
     * This method returns the SwitchPortSourceRouting.HopCount property 
     * value. This property is described as follows: 
     * 
     * The maximum number of routing descriptors allowed in an All Paths or 
     * Spanning Tree Explorer frames. 
     * 
     * @return	short	current HopCount property value
     * @exception	Exception	
     */
    public short getHopCount(){

    return this.hopCount;
    } // getHopCount

    /**
     * This method sets the SwitchPortSourceRouting.HopCount property value. 
     * This property is described as follows: 
     * 
     * The maximum number of routing descriptors allowed in an All Paths or 
     * Spanning Tree Explorer frames. 
     * 
     * @param	short	new HopCount property value
     * @exception	Exception	
     */
    public void setHopCount(short hopCount) {

    this.hopCount = hopCount;
    } // setHopCount


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property LocalSegment. 
     */
    private short localSegment;
    /**
     * This method returns the SwitchPortSourceRouting.LocalSegment property 
     * value. This property is described as follows: 
     * 
     * The segment number that uniquely identifies the segment to which this 
     * port is connected. Current source routing protocols limit this value 
     * to the range: 0 through 4095. (The value 0 is used by some management 
     * applications for special test cases.) A value of 65535 signifies that 
     * no segment number is assigned to this port. 
     * 
     * @return	short	current LocalSegment property value
     * @exception	Exception	
     */
    public short getLocalSegment(){

    return this.localSegment;
    } // getLocalSegment

    /**
     * This method sets the SwitchPortSourceRouting.LocalSegment property 
     * value. This property is described as follows: 
     * 
     * The segment number that uniquely identifies the segment to which this 
     * port is connected. Current source routing protocols limit this value 
     * to the range: 0 through 4095. (The value 0 is used by some management 
     * applications for special test cases.) A value of 65535 signifies that 
     * no segment number is assigned to this port. 
     * 
     * @param	short	new LocalSegment property value
     * @exception	Exception	
     */
    public void setLocalSegment(short localSegment) {

    this.localSegment = localSegment;
    } // setLocalSegment


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property BridgeNum. 
     */
    private short bridgeNum;
    /**
     * This method returns the SwitchPortSourceRouting.BridgeNum property 
     * value. This property is described as follows: 
     * 
     * A bridge number uniquely identifies a bridge when more than one bridge 
     * is used to span the same two segments. Current source routing 
     * protocols limit this value to the range: 0 through 15. A value of 
     * 65535 signifies that no bridge number is assigned to this bridge. 
     * 
     * @return	short	current BridgeNum property value
     * @exception	Exception	
     */
    public short getBridgeNum(){

    return this.bridgeNum;
    } // getBridgeNum

    /**
     * This method sets the SwitchPortSourceRouting.BridgeNum property value. 
     * This property is described as follows: 
     * 
     * A bridge number uniquely identifies a bridge when more than one bridge 
     * is used to span the same two segments. Current source routing 
     * protocols limit this value to the range: 0 through 15. A value of 
     * 65535 signifies that no bridge number is assigned to this bridge. 
     * 
     * @param	short	new BridgeNum property value
     * @exception	Exception	
     */
    public void setBridgeNum(short bridgeNum) {

    this.bridgeNum = bridgeNum;
    } // setBridgeNum


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property TargetSegment. 
     */
    private short targetSegment;
    /**
     * This method returns the SwitchPortSourceRouting.TargetSegment property 
     * value. This property is described as follows: 
     * 
     * The segment number that corresponds to the target segment to which this 
     * port is considered connected. Current source routing protocols limit 
     * this value to the range: 0 through 4095. (The value 0 is used by some 
     * management applications for special test cases.) A value of 65535 
     * signifies that no target segment is assigned to this port. 
     * 
     * @return	short	current TargetSegment property value
     * @exception	Exception	
     */
    public short getTargetSegment(){

    return this.targetSegment;
    } // getTargetSegment

    /**
     * This method sets the SwitchPortSourceRouting.TargetSegment property 
     * value. This property is described as follows: 
     * 
     * The segment number that corresponds to the target segment to which this 
     * port is considered connected. Current source routing protocols limit 
     * this value to the range: 0 through 4095. (The value 0 is used by some 
     * management applications for special test cases.) A value of 65535 
     * signifies that no target segment is assigned to this port. 
     * 
     * @param	short	new TargetSegment property value
     * @exception	Exception	
     */
    public void setTargetSegment(short targetSegment) {

    this.targetSegment = targetSegment;
    } // setTargetSegment


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property STESpanMode. 
     */

    public enum STESpanMode{
    AUTO_SPAN,
    DISABLED,
    FORCED
    }STESpanMode sTESpanMode;
    /**
     * This method returns the SwitchPortSourceRouting.STESpanMode property 
     * value. This property is described as follows: 
     * 
     * Determines how the port behaves when presented with a Spanning Tree 
     * Explorer frame. The value 'disabled(2)' indicates that the port will 
     * not accept or send Spanning Tree Explorer packets; any STE packets 
     * received will be silently discarded. The value 'forced(3)' indicates 
     * the port will always accept and propagate Spanning Tree Explorer 
     * frames. (This allows a manually configured Spanning Tree for this 
     * class of packet to be configured.) Note that unlike transparent 
     * bridging, it is not catastrophic to the network if there are loops. 
     * The value 'auto-span(1)' can only be returned by a bridge that both 
     * implements the Spanning Tree Protocol and has use of the protocol 
     * enabled on this port. The behavior of the port for Spanning Tree 
     * Explorer frames is determined by the value of the State property of 
     * the SwitchPortSpanningTree association for the port. If the port is in 
     * the 'forwarding' state, the frame will be accepted or propagated. 
     * Otherwise, it will be silently discarded. 
     * 
     * @return	short	current STESpanMode property value
     * @exception	Exception	
     */
    public STESpanMode getSTESpanMode(){

    return this.sTESpanMode;
    } // getSTESpanMode

    /**
     * This method sets the SwitchPortSourceRouting.STESpanMode property 
     * value. This property is described as follows: 
     * 
     * Determines how the port behaves when presented with a Spanning Tree 
     * Explorer frame. The value 'disabled(2)' indicates that the port will 
     * not accept or send Spanning Tree Explorer packets; any STE packets 
     * received will be silently discarded. The value 'forced(3)' indicates 
     * the port will always accept and propagate Spanning Tree Explorer 
     * frames. (This allows a manually configured Spanning Tree for this 
     * class of packet to be configured.) Note that unlike transparent 
     * bridging, it is not catastrophic to the network if there are loops. 
     * The value 'auto-span(1)' can only be returned by a bridge that both 
     * implements the Spanning Tree Protocol and has use of the protocol 
     * enabled on this port. The behavior of the port for Spanning Tree 
     * Explorer frames is determined by the value of the State property of 
     * the SwitchPortSpanningTree association for the port. If the port is in 
     * the 'forwarding' state, the frame will be accepted or propagated. 
     * Otherwise, it will be silently discarded. 
     * 
     * @param	short	new STESpanMode property value
     * @exception	Exception	
     */
    public void setSTESpanMode(STESpanMode sTESpanMode){

    this.sTESpanMode = sTESpanMode;
    } // setSTESpanMode



} // Class SwitchPortSourceRouting
