/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Fri Dec 17 
 * 13:56:59 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class SystemStatistics as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * SystemStatisticsBean Interface. The CIM class SystemStatistics is 
 * described as follows: 
 * 
 * SystemStatistics relates the SystemStatisticalInformation class to the 
 * System to which it applies. 
 */
public class SystemStatistics extends Statistics implements Serializable {

    /**
     * This constructor creates a SystemStatisticsBeanImpl Class which 
     * implements the SystemStatisticsBean Interface, and encapsulates the 
     * CIM class SystemStatistics in a Java Bean. The CIM class 
     * SystemStatistics is described as follows: 
     * 
     * SystemStatistics relates the SystemStatisticalInformation class to the 
     * System to which it applies. 
     */
    public SystemStatistics(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Stats. 
     */
    private SystemStatisticalInformation stats;
    /**
     * This method returns the SystemStatistics.Stats property value. This 
     * property is described as follows: 
     * 
     * The statistical object.
     * 
     * @return	CIM_SystemStatisticalInformation	current Stats 
     * property value 
     * @exception	Exception	
     */
    public SystemStatisticalInformation getStats(){

    return (SystemStatisticalInformation)stats;
    } // getStats

    /**
     * This method sets the SystemStatistics.Stats property value. This 
     * property is described as follows: 
     * 
     * The statistical object.
     * 
     * @param	CIM_SystemStatisticalInformation	new Stats 
     * property value 
     * @exception	Exception	
     */
    public void setStats(SystemStatisticalInformation stats) {

    this.stats = stats;
    } // setStats


    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property Element. 
     */
    private System element;
    /**
     * This method returns the SystemStatistics.Element property value. This 
     * property is described as follows: 
     * 
     * The System to which the statistics apply.
     * 
     * @return	CIM_System	current Element property value
     * @exception	Exception	
     */
    public System getElement(){

    return (System)element;
    } // getElement

    /**
     * This method sets the SystemStatistics.Element property value. This 
     * property is described as follows: 
     * 
     * The System to which the statistics apply.
     * 
     * @param	CIM_System	new Element property value
     * @exception	Exception	
     */
    public void setElement(System element) {

    this.element = element;
    } // setElement



} // Class SystemStatistics
