/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Fri Dec 17 
 * 13:56:59 CET 2010. 
 */

package net.i2cat.mantychore.model;

import java.util.*;
import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined 
 * in the CIM class TCPProtocolEndpoint as well as methods comparable to the 
 * invokeMethods defined for this class. This Class implements the 
 * TCPProtocolEndpointBean Interface. The CIM class TCPProtocolEndpoint is 
 * described as follows: 
 * 
 * A protocol endpoint that is dedicated to running TCP.
 */
public class TCPProtocolEndpoint extends ProtocolEndpoint implements 
    Serializable {

    /**
     * This constructor creates a TCPProtocolEndpointBeanImpl Class which 
     * implements the TCPProtocolEndpointBean Interface, and encapsulates the 
     * CIM class TCPProtocolEndpoint in a Java Bean. The CIM class 
     * TCPProtocolEndpoint is described as follows: 
     * 
     * A protocol endpoint that is dedicated to running TCP.
     */
    public TCPProtocolEndpoint(){};
    /**
     * The following constants are defined for use with the ValueMap/Values 
     * qualified property PortNumber. 
     */
    private int portNumber;
    /**
     * This method returns the TCPProtocolEndpoint.PortNumber property value. 
     * This property is described as follows: 
     * 
     * The TCP port number.
     * 
     * @return	int	current PortNumber property value
     * @exception	Exception	
     */
    public int getPortNumber(){

    return this.portNumber;
    } // getPortNumber

    /**
     * This method sets the TCPProtocolEndpoint.PortNumber property value. 
     * This property is described as follows: 
     * 
     * The TCP port number.
     * 
     * @param	int	new PortNumber property value
     * @exception	Exception	
     */
    public void setPortNumber(int portNumber) {

    this.portNumber = portNumber;
    } // setPortNumber




} // Class TCPProtocolEndpoint
