/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class VirtualSystemManagementService as well as methods
 * comparable to the invokeMethods defined for this class. This Class implements the VirtualSystemManagementServiceBean Interface. The CIM class
 * VirtualSystemManagementService is described as follows:
 * 
 * Service to define and manipulate virtual systems and their components
 */
public class VirtualSystemManagementService extends Service implements
		Serializable {

	/**
	 * This constructor creates a VirtualSystemManagementServiceBeanImpl Class which implements the VirtualSystemManagementServiceBean Interface, and
	 * encapsulates the CIM class VirtualSystemManagementService in a Java Bean. The CIM class VirtualSystemManagementService is described as follows:
	 * 
	 * Service to define and manipulate virtual systems and their components
	 */
	public VirtualSystemManagementService() {
	};
} // Class VirtualSystemManagementService
