/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class InstalledSoftwareIdentity as well as methods
 * comparable to the invokeMethods defined for this class. This Class implements the InstalledSoftwareIdentityBean Interface. The CIM class
 * InstalledSoftwareIdentity is described as follows:
 * 
 * The InstalledSoftwareIdentity association identifies the System on which a SoftwareIdentity is installed. This class is a corollary to
 * InstalledSoftwareElement, but deals with the asset aspects of software (as indicated by SoftwareIdentity), versus the deployment aspects (as
 * indicated by SoftwareElement).
 */
public class InstalledSoftwareIdentity extends Association implements
		Serializable {

	/**
	 * This constructor creates a InstalledSoftwareIdentityBeanImpl Class which implements the InstalledSoftwareIdentityBean Interface, and
	 * encapsulates the CIM class InstalledSoftwareIdentity in a Java Bean. The CIM class InstalledSoftwareIdentity is described as follows:
	 * 
	 * The InstalledSoftwareIdentity association identifies the System on which a SoftwareIdentity is installed. This class is a corollary to
	 * InstalledSoftwareElement, but deals with the asset aspects of software (as indicated by SoftwareIdentity), versus the deployment aspects (as
	 * indicated by SoftwareElement).
	 */
	public InstalledSoftwareIdentity() {
	};

	/**
	 * This method create an Association of the type InstalledSoftwareIdentity between one System object and SoftwareIdentity object
	 */
	public static InstalledSoftwareIdentity link(System
			system, SoftwareIdentity installedSoftware) {

		return (InstalledSoftwareIdentity) Association.link(InstalledSoftwareIdentity.class, system, installedSoftware);
	}// link

} // Class InstalledSoftwareIdentity
