//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 11:23:40 AM CET 
//


package org.opennaas.extensions.ofertie.ncl.monitoring.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientCount",
    "cpuLoad",
    "ramUsage"
})
@XmlRootElement(name = "server_metrics")
public class ServerMetrics {

    @XmlElement(name = "client_count")
    protected String clientCount;
    @XmlElement(name = "cpu_load")
    protected String cpuLoad;
    @XmlElement(name = "ram_usage")
    protected String ramUsage;

    /**
     * Gets the value of the clientCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCount() {
        return clientCount;
    }

    /**
     * Sets the value of the clientCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCount(String value) {
        this.clientCount = value;
    }

    /**
     * Gets the value of the cpuLoad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpuLoad() {
        return cpuLoad;
    }

    /**
     * Sets the value of the cpuLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpuLoad(String value) {
        this.cpuLoad = value;
    }

    /**
     * Gets the value of the ramUsage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRamUsage() {
        return ramUsage;
    }

    /**
     * Sets the value of the ramUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRamUsage(String value) {
        this.ramUsage = value;
    }

}
