/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;
import java.lang.Exception;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class NamedAddressCollection as well as methods comparable
 * to the invokeMethods defined for this class. This Class implements the NamedAddressCollectionBean Interface. The CIM class NamedAddressCollection
 * is described as follows:
 * 
 * A NamedAddressCollection groups ProtocolEndpoints/addresses and other network identifiers for the purposes of assigning a single name (i.e., an
 * alias). It is a subclass of SystemSpecificCollection to force the definition of the 'named collection' in the context of a System (for example,
 * either a ComputerSystem or an AdminDomain hosting a naming alias).
 */
public class NamedAddressCollection extends SystemSpecificCollection
		implements Serializable {

	/**
	 * This constructor creates a NamedAddressCollectionBeanImpl Class which implements the NamedAddressCollectionBean Interface, and encapsulates the
	 * CIM class NamedAddressCollection in a Java Bean. The CIM class NamedAddressCollection is described as follows:
	 * 
	 * A NamedAddressCollection groups ProtocolEndpoints/addresses and other network identifiers for the purposes of assigning a single name (i.e., an
	 * alias). It is a subclass of SystemSpecificCollection to force the definition of the 'named collection' in the context of a System (for example,
	 * either a ComputerSystem or an AdminDomain hosting a naming alias).
	 */
	public NamedAddressCollection() {
	};

	/**
	 * The following constants are defined for use with the ValueMap/Values qualified property collectionAlias.
	 */
	private String	collectionAlias;

	/**
	 * This method returns the NamedAddressCollection.collectionAlias property value. This property is described as follows:
	 * 
	 * A name (alias) for the NamedAddressCollection which is unique in the context of the hosting System.
	 * 
	 * @return String current collectionAlias property value
	 * @exception Exception
	 */
	public String getCollectionAlias() {

		return this.collectionAlias;
	} // getCollectionAlias

	/**
	 * This method sets the NamedAddressCollection.collectionAlias property value. This property is described as follows:
	 * 
	 * A name (alias) for the NamedAddressCollection which is unique in the context of the hosting System.
	 * 
	 * @param String
	 *            new collectionAlias property value
	 * @exception Exception
	 */
	public void setCollectionAlias(String collectionAlias) {

		this.collectionAlias = collectionAlias;
	} // setCollectionAlias

} // Class NamedAddressCollection
