/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class SettingForSystem as well as methods comparable to the
 * invokeMethods defined for this class. This Class implements the SettingForSystemBean Interface. The CIM class SettingForSystem is described as
 * follows:
 * 
 * CIM_SettingForSystem defines a Setting in the context of the System on which it is located.
 */
public class SettingForSystem extends HostedDependency implements Serializable
{

	/**
	 * This constructor creates a SettingForSystemBeanImpl Class which implements the SettingForSystemBean Interface, and encapsulates the CIM class
	 * SettingForSystem in a Java Bean. The CIM class SettingForSystem is described as follows:
	 * 
	 * CIM_SettingForSystem defines a Setting in the context of the System on which it is located.
	 */
	public SettingForSystem() {
	};

	/**
	 * This method create an Association of the type SettingForSystem between one System object and SystemSetting object
	 */
	public static SettingForSystem link(System antecedent, SystemSetting
			dependent) {

		return (SettingForSystem) Association.link(SettingForSystem.class, antecedent, dependent);
	}// link

} // Class SettingForSystem
