/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class Specific802dot1QVLANService as well as methods
 * comparable to the invokeMethods defined for this class. This Class implements the Specific802dot1QVLANServiceBean Interface. The CIM class
 * Specific802dot1QVLANService is described as follows:
 * 
 * This class is deprecated following discussion as to the need of a modeling a 802.1Q as a service. It was determined that a 802.1Q service was not
 * needed. If a switch supports 802.1Q, an instance of this class should be instantiated in the switch. If the switch supports GVRP, this class
 * represents the function that the switch performs with respect to GVRP.
 */
@Deprecated
public class Specific802dot1QVLANService extends VLANService implements
		Serializable {

	/**
	 * This constructor creates a Specific802dot1QVLANServiceBeanImpl Class which implements the Specific802dot1QVLANServiceBean Interface, and
	 * encapsulates the CIM class Specific802dot1QVLANService in a Java Bean. The CIM class Specific802dot1QVLANService is described as follows:
	 * 
	 * This class is deprecated following discussion as to the need of a modeling a 802.1Q as a service. It was determined that a 802.1Q service was
	 * not needed. If a switch supports 802.1Q, an instance of this class should be instantiated in the switch. If the switch supports GVRP, this
	 * class represents the function that the switch performs with respect to GVRP.
	 */
	public Specific802dot1QVLANService() {
	};
} // Class Specific802dot1QVLANService
