/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class TransparentBridgingStaticForwarding as well as methods
 * comparable to the invokeMethods defined for this class. This Class implements the TransparentBridgingStaticForwardingBean Interface. The CIM class
 * TransparentBridgingStaticForwarding is described as follows:
 * 
 * This association links an instance of the Transparent BridgingService to the entries of its static (destination-address filtering) database.
 */
public class TransparentBridgingStaticForwarding extends Dependency implements
		Serializable {

	/**
	 * This constructor creates a TransparentBridgingStaticForwardingBeanImpl Class which implements the TransparentBridgingStaticForwardingBean
	 * Interface, and encapsulates the CIM class TransparentBridgingStaticForwarding in a Java Bean. The CIM class TransparentBridgingStaticForwarding
	 * is described as follows:
	 * 
	 * This association links an instance of the Transparent BridgingService to the entries of its static (destination-address filtering) database.
	 */
	public TransparentBridgingStaticForwarding() {
	};

	/**
	 * This method create an Association of the type TransparentBridgingStaticForwarding between one TransparentBridgingService object and
	 * StaticForwardingEntry object
	 */
	public static TransparentBridgingStaticForwarding
			link(TransparentBridgingService antecedent, StaticForwardingEntry
					dependent) {

		return (TransparentBridgingStaticForwarding) Association.link(TransparentBridgingStaticForwarding.class, antecedent, dependent);
	}// link

} // Class TransparentBridgingStaticForwarding
