/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class DeviceStatistics as well as methods comparable to the
 * invokeMethods defined for this class. This Class implements the DeviceStatisticsBean Interface. The CIM class DeviceStatistics is described as
 * follows:
 * 
 * DeviceStatistics relates the DeviceStatisticalInformation class to the LogicalDevice to which it applies.
 */
public class DeviceStatistics extends Statistics implements Serializable {

	/**
	 * This constructor creates a DeviceStatisticsBeanImpl Class which implements the DeviceStatisticsBean Interface, and encapsulates the CIM class
	 * DeviceStatistics in a Java Bean. The CIM class DeviceStatistics is described as follows:
	 * 
	 * DeviceStatistics relates the DeviceStatisticalInformation class to the LogicalDevice to which it applies.
	 */
	public DeviceStatistics() {
	};

	/**
	 * This method create an Association of the type DeviceStatistics between one DeviceStatisticalInformation object and LogicalDevice object
	 */
	public static DeviceStatistics link(DeviceStatisticalInformation
			stats, LogicalDevice element) {

		return (DeviceStatistics) Association.link(DeviceStatistics.class, stats, element);
	}// link

} // Class DeviceStatistics
