/**
 * This file was auto-generated by mofcomp -j version 1.0.0 on Wed Jan 12
 * 09:21:06 CET 2011.
 */

package org.opennaas.extensions.router.model;

import java.io.*;

/**
 * This Class contains accessor and mutator methods for all properties defined in the CIM class Statistics as well as methods comparable to the
 * invokeMethods defined for this class. This Class implements the StatisticsBean Interface. The CIM class Statistics is described as follows:
 * 
 * CIM_Statistics is an association that relates Managed Elements to the StatisticalGroup(s) that apply to them.
 */
public class Statistics extends Association implements Serializable {

	/**
	 * This constructor creates a StatisticsBeanImpl Class which implements the StatisticsBean Interface, and encapsulates the CIM class Statistics in
	 * a Java Bean. The CIM class Statistics is described as follows:
	 * 
	 * CIM_Statistics is an association that relates Managed Elements to the StatisticalGroup(s) that apply to them.
	 */
	public Statistics() {
	};

	/**
	 * This method create an Association of the type Statistics between one StatisticalInformation object and ManagedElement object
	 */
	public static Statistics link(StatisticalInformation stats, ManagedElement
			element) {

		return (Statistics) Association.link(Statistics.class, stats, element);
	}// link

} // Class Statistics
